
[project_pages_paths]
ABOUT = "frontend/pages/about/page_about.py"
BINARY_SEARCH = "frontend/pages/binary_search/page_binary_search.py"
INSERTION_SORT = "frontend/pages/insertion_sort/page_insertion_sort.py"
